### ISSUE TITLE
Question: How does this workspace works?

### ISSUE THREAD

**Issue by TheFern2** [nirenjan/g710plus-linux#1]
Hi, I have a g613 keyboard which has G1-G6, no M keys. Everything works with generic driveer except G keys they are hardcoded mapped to F1-F6. Even the volume, and playback keys work.

I am going to try to use this for g613, but I don't see much code on this repo. Is libg710 folder all needed to drive the G keys? I don't know much about userspaces or how to use them, I've tried other drivers from other logitech keyboards with no luck.

**Comment by nirenjan** [comment]
Honestly, I have no idea - and this project is nowhere near complete.

I know that the G710 sends in a specific USB report when the G or M keys are pressed, you might have better luck investigating this angle. Check the hidraw input for the keyboard. If it works similar to the G710, then you should have two separate hidraw events, one for the regular keyboard, another for the G keys and volume/playback keys. Even if there's a single hidraw input, then you should have separate report IDs for the different sets of keys. The USB HID report descriptor is king here - it will tell the kernel how to interpret the hidraw events.

**Comment by TheFern2** [comment]
Ok, thanks for the hint on hid report.
